### ISSUE TITLE
Compilation to apk

### ISSUE THREAD

**Issue by Rs20232023** [buttim/TrovaLaSonda#1]
Hi buttim,
How to compile your software into .apk file?

**Comment by buttim** [comment]
Hi. Almost straightforward using android studio. Unic exception the Bluetooth serial library, which I modified on purpose. I was too lazy to publish the artifact as I should have. So you will have to fiddle a bit. I'm not at home right now but I'll make a check in a few hours and let you know

**Comment by buttim** [comment]
Also keep in mind that if you don't need to modify the app you can install it from Google play

**Comment by buttim** [comment]
I can confirm the situation I described earlier. You should clone the repository for the bluetooth serial library from my fork [here](https://github.com/buttim/android-bluetooth-serial)

**Comment by Rs20232023** [comment]
Thank you for your answer.
I have already installed your software from Google Play. Very very good software.
I would like to change a few details for private use or know how to do it. Unfortunately, I do not have the knowledge to do it.
1. Predictors are set to a fall speed of 5m/s. Radiosondes in my area usually fall 12m/s.
2. I would like to enlarge the font and numbers in the bottom bar (radiosonde type and frequency, H, V, Vs) - I have a small screen and poor eyesight.

**Comment by buttim** [comment]
Yes the predictions thing is a bit rigid. I'm trying to keep the app as simple as possible. I do not want it to have lots of customization. This would be too much work for me and possibly confusing for many users. But I admit the current situation is a bit crude. If you are not an Android programmer I suggest you do not mess with the code, it would be a headache. On the other side small details in the user interface like font size and a mere constant would be feasible, it depends on how much time you want to spend in learning things. My eyesight is not good at all, and that was the whole point in starting to write my own app.
If you have suggestions I can think of incorporating them in the app, provided that they are not too complex to implement and they are somehow useful for the whole community. Feel free to open other issues to suggest improvements. For now I will close this one
